apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secret"
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  S3_MAPS_ACCESS_KEY: {{ .Values.s3Maps.accessKey | default "" | b64enc}}
  S3_MAPS_SECRET_KEY: {{ .Values.s3Maps.secretKey | default "" | b64enc}}