# Default values for CFmapserver Helm chart. This is a YAML-formatted file.

# S3 configuration settings
s3Maps:
  host: 'https://s3.waw3-1.cloudferro.com'
  bucket: ''
  accessKey: ''
  secretKey: ''

# cron job schedule in cron format
cronJobSchedule: '0 0 * * *' # the default refreshes every minute

# MapServer Docker image setting
image:
  repository: camptocamp/mapserver
  tag: '7.6-20-04'
  mapFilesPath: '/etc/mapserver'

# Init container image settings
initImage:
  repository: cfro/mapserver-init
  tag: '0.1.1'

# Service settings
service:
  type: LoadBalancer
  port: 80

# Pod replication and scaling settings
replicaCount: 1
resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10